from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class EngineMetadata(BaseModel):
    """
    Tracks the version and global capabilities of the Analytics Engine.
    Used for reproducibility and API metadata.
    """
    name: str = "ProcessIQ Analytics Engine"
    version: str = "1.0.0"
    supported_operations: int = 0
    dependencies: List[str] = ["pandas", "scikit-learn", "numpy"]
    quality_dimensions: List[str] = ["Completeness", "Consistency", "Validity", "Accuracy", "Uniqueness", "Timeliness", "Integrity"]

class OperationMetadata(BaseModel):
    """
    Rich metadata describing a specific preprocessing operation.
    Enables automatic documentation generation and dynamic LLM planning.
    """
    name: str
    category: str
    description: str
    input_types: List[str]
    output_types: List[str]
    parameters: Dict[str, Any]
    dependencies: List[str] = []
    
    time_complexity: str  # e.g., "O(N)"
    memory_complexity: str # e.g., "O(1)"
    risk_level: str        # "Low", "Medium", "High"
    expected_quality_gain: str # e.g., "High - Eliminates severe outliers"
    
    is_deterministic: bool = True
    is_reversible: bool = False
    supports_rollback: bool = True
    supports_parallelism: bool = False
    
    examples: List[str] = []
    documentation_url: Optional[str] = None

class RecommendationCard(BaseModel):
    """
    A rich recommendation output generated by the Recommendation Engine.
    Consumed by the frontend UI and the LLM Context Builder.
    """
    operation_name: str
    confidence_score: float # 0.0 to 100.0
    expected_quality_gain: float
    execution_cost: str # "Low", "Medium", "High"
    runtime_estimate_ms: Optional[float] = None
    memory_estimate_mb: Optional[float] = None
    risk_level: str # "Low", "Medium", "High"
    
    pros: List[str]
    cons: List[str]
    alternatives: List[str]
    affected_columns: List[str]
    references: List[str] = []

class FeatureMetadata(BaseModel):
    """
    Tracks the lineage and metadata of engineered features.
    Provides excellent explainability and is consumed directly by Feature Selection.
    """
    feature_name: str
    source_columns: List[str]
    engineering_method: str
    transformation_formula: str
    dependencies: List[str] = []
    creation_time: str
    version: str = "1.0"
    
    # Selection Phase Extensions
    is_selected: bool = False
    importance_score: Optional[float] = None
    selection_reason: Optional[str] = None
    selection_history: Dict[str, Any] = {} # e.g. {"VarianceThreshold": 0.82, "MI": 0.71, "Boruta": "Confirmed"}
    final_rank: Optional[int] = None
    final_confidence: Optional[float] = None

