from typing import List, Dict, Any

class AIExplainer:
    """
    The Explainer Agent.
    Receives deterministic IDRS metrics and rule engine recommendations.
    Generates a natural language summary explaining the dataset health and why specific actions are recommended.
    """
    def __init__(self, llm_client=None):
        self.llm_client = llm_client
        
    def build_prompt(self, idrs_score: float, recommendations: List[Dict[str, Any]]) -> str:
        prompt = f"""
You are an Industrial Data Quality Assistant.
The dataset has achieved an Industrial Dataset Readiness Score (IDRS) of {idrs_score:.1f}/100.

Here are the deterministic recommendations generated by our Rule Engine:
"""
        for rec in recommendations:
            prompt += f"- Action: {rec['action']} (Confidence: {rec['confidence']}%). Reason: {rec['reason']}\n"
            
        prompt += """
Please provide a concise, professional summary for the data engineer explaining the overall health of this dataset and summarizing the recommended actions. Do not invent any new preprocessing methods.
"""
        return prompt
